### PR TITLE
Simpler array bounds checking

### PR DESCRIPTION
**Pull request by ZevEisenberg**
## Steps
- [x] Add your name or username and a link to your GitHub profile into the [Contributors.md][1] file.
- [ ] Build the project on your machine. If it does not compile, fix the errors.
- [x] Describe the purpose and approach of your pull request below.
- [x] Submit the pull request. Thank you very much for your contribution!

## Purpose

This is a slightly simpler and possibly more idiomatic way to check array bounds using the array's built-in `indices` collection.

## Approach

See above.

[1]:	/Contributors.md

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
I wasn't able to build on my machine, possibly because I'm on a Mac?

**Review by david-swift — APPROVED** [review]
Thank you! Could you maybe share some information about your problem on macOS, maybe in the discussions? I tried this library on macOS the last time some months ago, and the build succeeded, so it probably isn't a general problem of the library itself, but one of the system/configuration.

**Comment by ZevEisenberg** [comment]
Apologies for the delay! Here's a screenshot of the errors I see, and some detail on the first one in the build log. I'm assuming I need some dependency installed, but the readme didn't mention anything that I could see.

**Comment by david-swift** [comment]
This is probably the same problem as reported in https://github.com/AparokshaUI/adwaita-swift/issues/32. Unfortunately, we haven't yet been able to fix it. Maybe you could try the steps in https://github.com/AparokshaUI/adwaita-swift/issues/11#issuecomment-2026804538, I don't know whether this helps (in general, I'd recommend installing Linux on the device or in a VM to work with Libadwaita).

**Pull request merged**
